# Generated by Django 4.2.5 on 2025-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', '未着手'), ('in_progress', '進行中'), ('done', '完了')], default='todo', max_length=20),
        ),
    ]
